Repository 9oormthon-univ/2024_BEOTKKOTTHON_TEAM_23_BE, pull requests merged in 2024-03, with the labels that each got.

#2 🗃 ERD 반영 Domain, Repository 구현, 보일러플레이트 수정
  src/main/java/com/beotkkotthon/areyousleeping/config/SwaggerConfig.java
  src/main/java/com/beotkkotthon/areyousleeping/controller/AuthController.java
  src/main/java/com/beotkkotthon/areyousleeping/domain/Achievement.java
  src/main/java/com/beotkkotthon/areyousleeping/domain/AllNighters.java
  src/main/java/com/beotkkotthon/areyousleeping/domain/Following.java
  src/main/java/com/beotkkotthon/areyousleeping/domain/Mission.java
  src/main/java/com/beotkkotthon/areyousleeping/domain/Team.java
  src/main/java/com/beotkkotthon/areyousleeping/domain/UserTeam.java
  src/main/java/com/beotkkotthon/areyousleeping/intercepter/post/ResponseInterceptor.java
  src/main/java/com/beotkkotthon/areyousleeping/repository/AchievementRepository.java
  src/main/java/com/beotkkotthon/areyousleeping/repository/AllNightersRepository.java
  src/main/java/com/beotkkotthon/areyousleeping/repository/FollowingRepository.java
  src/main/java/com/beotkkotthon/areyousleeping/repository/MissionRepository.java
  src/main/java/com/beotkkotthon/areyousleeping/repository/TeamRepository.java
  src/main/java/com/beotkkotthon/areyousleeping/repository/UserTeamRepository.java
  src/main/java/com/beotkkotthon/areyousleeping/security/handler/login/DefaultSuccessHandler.java
  src/main/java/com/beotkkotthon/areyousleeping/security/handler/logout/CustomLogoutResultHandler.java
Labels: feature, 동겸

#3 🗃️ Domain id 변경 ex) teamId -> id
  .gitignore
  src/main/java/com/beotkkotthon/areyousleeping/config/CorsConfig.java
  src/main/java/com/beotkkotthon/areyousleeping/domain/Achievement.java
  src/main/java/com/beotkkotthon/areyousleeping/domain/AllNighters.java
  src/main/java/com/beotkkotthon/areyousleeping/domain/Following.java
  src/main/java/com/beotkkotthon/areyousleeping/domain/Mission.java
  src/main/java/com/beotkkotthon/areyousleeping/domain/Team.java
  src/main/java/com/beotkkotthon/areyousleeping/domain/User.java
  src/main/java/com/beotkkotthon/areyousleeping/domain/UserTeam.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/response/UserDetailDto.java
  src/main/java/com/beotkkotthon/areyousleeping/repository/UserRepository.java
  src/main/java/com/beotkkotthon/areyousleeping/security/info/UserPrincipal.java
  src/main/java/com/beotkkotthon/areyousleeping/service/AuthService.java
Labels: 동겸, fix

#5 ✨ 채팅 구현 및 테스팅 완료
  build.gradle
  src/main/java/com/beotkkotthon/areyousleeping/config/MongoConfig.java
  src/main/java/com/beotkkotthon/areyousleeping/config/WebSocketConfig.java
  src/main/java/com/beotkkotthon/areyousleeping/constants/Constants.java
  src/main/java/com/beotkkotthon/areyousleeping/controller/ChatController.java
  src/main/java/com/beotkkotthon/areyousleeping/controller/TeamController.java
  src/main/java/com/beotkkotthon/areyousleeping/domain/User.java
  src/main/java/com/beotkkotthon/areyousleeping/domain/nosql/ChatMessage.java
  src/main/java/com/beotkkotthon/areyousleeping/domain/nosql/ChatMessageList.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/request/ChatMessageDto.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/request/TeamCreateRequestDto.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/request/UserUpdateDto.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/response/ChatMessageListDto.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/response/ChatMessageResponseDto.java
  src/main/java/com/beotkkotthon/areyousleeping/exception/ErrorCode.java
  src/main/java/com/beotkkotthon/areyousleeping/repository/ChatMessageListRepository.java
  src/main/java/com/beotkkotthon/areyousleeping/repository/UserRepository.java
  src/main/java/com/beotkkotthon/areyousleeping/security/config/SecurityConfig.java
  src/main/java/com/beotkkotthon/areyousleeping/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/beotkkotthon/areyousleeping/security/provider/JwtAuthenticationManager.java
  src/main/java/com/beotkkotthon/areyousleeping/security/provider/JwtAuthenticationProvider.java
  src/main/java/com/beotkkotthon/areyousleeping/security/service/CustomUserDetailService.java
  src/main/java/com/beotkkotthon/areyousleeping/service/ChatMessageService.java
  src/main/java/com/beotkkotthon/areyousleeping/service/TeamService.java
  src/main/java/com/beotkkotthon/areyousleeping/service/UserService.java
  src/main/resources/docker-compose.yml
Labels: feature, 동겸

#7 ✨ 상태가 active인 팀원에게 돌발적인 시각(기본 50분 + 최대 30분)에 동일 미션 발행
  build.gradle
  src/main/java/com/beotkkotthon/areyousleeping/service/MissionService.java
Labels: feature, 동겸

#9 ✨ 미션 결과 저장, 미션 타임라인 조회 api 구현
  src/main/java/com/beotkkotthon/areyousleeping/controller/ChatController.java
  src/main/java/com/beotkkotthon/areyousleeping/controller/MissionController.java
  src/main/java/com/beotkkotthon/areyousleeping/controller/TeamController.java
  src/main/java/com/beotkkotthon/areyousleeping/domain/Mission.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/request/ChatMessageDto.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/request/MissionImageDto.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/request/MissionTextDto.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/request/TeamCreateRequestDto.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/request/UserUpdateDto.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/response/MissionDto.java
  src/main/java/com/beotkkotthon/areyousleeping/repository/MissionRepository.java
  src/main/java/com/beotkkotthon/areyousleeping/repository/UserTeamRepository.java
  src/main/java/com/beotkkotthon/areyousleeping/service/MissionService.java
  src/main/java/com/beotkkotthon/areyousleeping/service/TeamService.java
  src/main/java/com/beotkkotthon/areyousleeping/service/UserService.java
  src/main/java/com/beotkkotthon/areyousleeping/utility/ImageUtil.java
  src/test/java/com/beotkkotthon/areyousleeping/AreYouSleepingApplicationTests.java
Labels: feature, 동겸

#12 ✨ 팀 관련 API 구현(팀 생성, 팀 참여하기, 팀 나가기)
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/com/beotkkotthon/areyousleeping/controller/TeamController.java
  src/main/java/com/beotkkotthon/areyousleeping/controller/UserTeamController.java
  src/main/java/com/beotkkotthon/areyousleeping/domain/Team.java
  src/main/java/com/beotkkotthon/areyousleeping/domain/UserTeam.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/request/TeamSaveDto.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/request/UserActiveStatusDto.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/request/UserUpdateDto.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/response/TeamResponseDto.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/response/UserTeamResponseDto.java
  src/main/java/com/beotkkotthon/areyousleeping/repository/UserTeamRepository.java
  src/main/java/com/beotkkotthon/areyousleeping/service/TeamService.java
  src/main/java/com/beotkkotthon/areyousleeping/service/UserTeamService.java
  src/main/resources/application-local.yml
Labels: feature, 다은

#15 🐛 클라이언트 사이드 소셜로그인 인증 반영하여 OAuth 로직 수정
  .gitignore
  Dockerfile
  src/main/java/com/beotkkotthon/areyousleeping/config/CorsConfig.java
  src/main/java/com/beotkkotthon/areyousleeping/config/SwaggerConfig.java
  src/main/java/com/beotkkotthon/areyousleeping/constants/Constants.java
  src/main/java/com/beotkkotthon/areyousleeping/controller/AuthController.java
  src/main/java/com/beotkkotthon/areyousleeping/controller/ChatController.java
  src/main/java/com/beotkkotthon/areyousleeping/controller/MissionController.java
  src/main/java/com/beotkkotthon/areyousleeping/controller/UserController.java
  src/main/java/com/beotkkotthon/areyousleeping/controller/UserTeamController.java
  src/main/java/com/beotkkotthon/areyousleeping/domain/Achievement.java
  src/main/java/com/beotkkotthon/areyousleeping/domain/User.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/request/OauthLoginDto.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/request/OauthSignUpDto.java
  src/main/java/com/beotkkotthon/areyousleeping/repository/UserRepository.java
  src/main/java/com/beotkkotthon/areyousleeping/security/config/SecurityConfig.java
  src/main/java/com/beotkkotthon/areyousleeping/security/handler/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/beotkkotthon/areyousleeping/security/handler/jwt/JwtAuthEntryPoint.java
  src/main/java/com/beotkkotthon/areyousleeping/security/handler/login/DefaultSuccessHandler.java
  src/main/java/com/beotkkotthon/areyousleeping/security/handler/login/Oauth2FailureHandler.java
  src/main/java/com/beotkkotthon/areyousleeping/security/handler/login/Oauth2SuccessHandler.java
  src/main/java/com/beotkkotthon/areyousleeping/security/handler/logout/CustomLogoutResultHandler.java
  src/main/java/com/beotkkotthon/areyousleeping/security/info/AbstractAuthenticationFailure.java
  src/main/java/com/beotkkotthon/areyousleeping/security/info/AppleOauth2UserInfo.java
  src/main/java/com/beotkkotthon/areyousleeping/security/info/AuthenticationResponse.java
  src/main/java/com/beotkkotthon/areyousleeping/security/info/KakaoOauth2UserInfo.java
  src/main/java/com/beotkkotthon/areyousleeping/security/info/UserPrincipal.java
  src/main/java/com/beotkkotthon/areyousleeping/security/info/factory/Oauth2UserInfo.java
  src/main/java/com/beotkkotthon/areyousleeping/security/info/factory/Oauth2UserInfoFactory.java
  src/main/java/com/beotkkotthon/areyousleeping/security/service/CustomOauth2UserDetailService.java
  src/main/java/com/beotkkotthon/areyousleeping/service/AuthService.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/main/resources/docker-compose.yml
Labels: bug, 동겸, fix

#20 ✨ UserTeam관련 조회 API
  src/main/java/com/beotkkotthon/areyousleeping/controller/AchievementController.java
  src/main/java/com/beotkkotthon/areyousleeping/controller/FollowingController.java
  src/main/java/com/beotkkotthon/areyousleeping/controller/UserTeamController.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/response/TeamMemberInfoDto.java
  src/main/java/com/beotkkotthon/areyousleeping/repository/AchievementRepository.java
  src/main/java/com/beotkkotthon/areyousleeping/repository/UserTeamRepository.java
  src/main/java/com/beotkkotthon/areyousleeping/service/AchievementService.java
  src/main/java/com/beotkkotthon/areyousleeping/service/UserTeamService.java
Labels: feature, 다은

#21 ✨ 팀 목록조회 무한스크롤 및 필터링 구현 / TeamResponseDto 및 관련 로직 리펙토링
  src/main/java/com/beotkkotthon/areyousleeping/controller/TeamController.java
  src/main/java/com/beotkkotthon/areyousleeping/domain/specification/TeamSpecifications.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/response/TeamResponseDto.java
  src/main/java/com/beotkkotthon/areyousleeping/repository/TeamRepository.java
  src/main/java/com/beotkkotthon/areyousleeping/service/TeamService.java
Labels: feature, 동겸

#23 🚑 UserTeam 테이블에 유저가 속했던 팀 아이디 보존하는 historyTeamId 컬럼 추가 / 팀에 속해있을 때의 팀 생성 예외처리
  src/main/java/com/beotkkotthon/areyousleeping/controller/TeamController.java
  src/main/java/com/beotkkotthon/areyousleeping/domain/User.java
  src/main/java/com/beotkkotthon/areyousleeping/domain/UserTeam.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/request/AuthSignUpDto.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/request/ChatMessageDto.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/response/UserTeamResponseDto.java
  src/main/java/com/beotkkotthon/areyousleeping/exception/ErrorCode.java
  src/main/java/com/beotkkotthon/areyousleeping/repository/UserTeamRepository.java
  src/main/java/com/beotkkotthon/areyousleeping/service/TeamService.java
  src/main/java/com/beotkkotthon/areyousleeping/service/UserTeamService.java
Labels: bug, 동겸, fix

#24 🐛 historyTeamId 로직에 반영 / 미션 발행 조건 수정
  build.gradle
  src/main/java/com/beotkkotthon/areyousleeping/constants/Constants.java
  src/main/java/com/beotkkotthon/areyousleeping/domain/AllNighters.java
  src/main/java/com/beotkkotthon/areyousleeping/domain/UserTeam.java
  src/main/java/com/beotkkotthon/areyousleeping/exception/ErrorCode.java
  src/main/java/com/beotkkotthon/areyousleeping/repository/AllNightersRepository.java
  src/main/java/com/beotkkotthon/areyousleeping/repository/UserTeamRepository.java
  src/main/java/com/beotkkotthon/areyousleeping/service/MissionService.java
  src/main/java/com/beotkkotthon/areyousleeping/service/TeamService.java
  src/main/java/com/beotkkotthon/areyousleeping/service/UserTeamService.java
Labels: 동겸, fix

#27 ✨ 팔로워 조회 API & 팀원 추방하기 구현
  src/main/java/com/beotkkotthon/areyousleeping/controller/FollowingController.java
  src/main/java/com/beotkkotthon/areyousleeping/controller/UserTeamController.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/response/FollowingInfoDto.java
  src/main/java/com/beotkkotthon/areyousleeping/exception/ErrorCode.java
  src/main/java/com/beotkkotthon/areyousleeping/repository/FollowingRepository.java
  src/main/java/com/beotkkotthon/areyousleeping/service/FollowingService.java
  src/main/java/com/beotkkotthon/areyousleeping/service/UserTeamService.java
Labels: feature, 다은

#29 ✨ 밤샘 기록 조회(밤샘 달력) api 구현
  src/main/java/com/beotkkotthon/areyousleeping/controller/AllNightersController.java
  src/main/java/com/beotkkotthon/areyousleeping/domain/UserTeam.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/response/AllNightersDto.java
  src/main/java/com/beotkkotthon/areyousleeping/repository/AllNightersRepository.java
  src/main/java/com/beotkkotthon/areyousleeping/service/AllNightersService.java
Labels: feature, 동겸

#30 🐛 MissionTimeLine 조회 로직 HistoryTeamId 기반으로 변경
  src/main/java/com/beotkkotthon/areyousleeping/dto/response/AllNightersDto.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/response/MissionDto.java
  src/main/java/com/beotkkotthon/areyousleeping/repository/UserTeamRepository.java
  src/main/java/com/beotkkotthon/areyousleeping/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/beotkkotthon/areyousleeping/security/provider/JwtAuthenticationManager.java
  src/main/java/com/beotkkotthon/areyousleeping/security/provider/JwtAuthenticationProvider.java
  src/main/java/com/beotkkotthon/areyousleeping/security/service/CustomUserDetailService.java
  src/main/java/com/beotkkotthon/areyousleeping/service/AllNightersService.java
  src/main/java/com/beotkkotthon/areyousleeping/service/MissionService.java
Labels: 동겸, fix

#31 ✨ 칭호 갱신 로직 구현 / isSecret 적용 안되던 버그 수정
  src/main/java/com/beotkkotthon/areyousleeping/controller/AchievementController.java
  src/main/java/com/beotkkotthon/areyousleeping/controller/TeamController.java
  src/main/java/com/beotkkotthon/areyousleeping/domain/Achievement.java
  src/main/java/com/beotkkotthon/areyousleeping/domain/AllNighters.java
  src/main/java/com/beotkkotthon/areyousleeping/domain/Mission.java
  src/main/java/com/beotkkotthon/areyousleeping/domain/Team.java
  src/main/java/com/beotkkotthon/areyousleeping/domain/UserTeam.java
  src/main/java/com/beotkkotthon/areyousleeping/domain/specification/TeamSpecifications.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/request/TeamSaveDto.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/response/AchievementDto.java
  src/main/java/com/beotkkotthon/areyousleeping/service/AchievementService.java
  src/main/java/com/beotkkotthon/areyousleeping/service/TeamService.java
Labels: feature, 동겸, fix

#32 ✨ 밤샘 메이트 조회 return 값 수정 & 방장 재설정 로직
  src/main/java/com/beotkkotthon/areyousleeping/domain/UserTeam.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/response/TeamMemberInfoDto.java
  src/main/java/com/beotkkotthon/areyousleeping/repository/UserTeamRepository.java
  src/main/java/com/beotkkotthon/areyousleeping/service/UserTeamService.java
Labels: 다은, fix

#34 ✨ 팀 채팅 기록 불러오기에 페이지네이션 추가 / 변경된 유저 정보가 채팅 기록 불러오기에 적용되게 수정
  src/main/java/com/beotkkotthon/areyousleeping/controller/ChatController.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/response/ChatMessageListDto.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/response/ChatMessageResponseDto.java
  src/main/java/com/beotkkotthon/areyousleeping/service/ChatMessageService.java
  src/main/java/com/beotkkotthon/areyousleeping/service/UserTeamService.java
Labels: feature, 동겸, fix

#36 🐛 fix: 코드 리펙토링 / 밤샘기록 null point exception 해결
  src/main/java/com/beotkkotthon/areyousleeping/controller/AchievementController.java
  src/main/java/com/beotkkotthon/areyousleeping/controller/UserController.java
  src/main/java/com/beotkkotthon/areyousleeping/controller/UserTeamController.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/request/ChatMessageDto.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/request/MissionImageDto.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/request/MissionTextDto.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/request/OauthLoginDto.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/request/TeamCreateRequestDto.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/request/TeamSaveDto.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/request/UserUpdateDto.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/response/AchievementDto.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/response/AllNightersDto.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/response/ChatMessageListDto.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/response/ChatMessageResponseDto.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/response/CommonUserSourseDto.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/response/FollowingInfoDto.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/response/FollowingResponseDto.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/response/MissionDto.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/response/TeamMemberInfoDto.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/response/UserDetailDto.java
  src/main/java/com/beotkkotthon/areyousleeping/dto/response/UserTeamResponseDto.java
  src/main/java/com/beotkkotthon/areyousleeping/repository/UserTeamRepository.java
  src/main/java/com/beotkkotthon/areyousleeping/service/AchievementService.java
  src/main/java/com/beotkkotthon/areyousleeping/service/AllNightersService.java
  src/main/java/com/beotkkotthon/areyousleeping/service/UserService.java
  src/main/java/com/beotkkotthon/areyousleeping/service/UserTeamService.java
Labels: 동겸, fix

#37 🚑 fix: 유저 기본이미지 추가
  src/main/java/com/beotkkotthon/areyousleeping/constants/Constants.java
  src/main/java/com/beotkkotthon/areyousleeping/domain/User.java
Labels: 동겸
